// Materials Database
const Materials = {
    WEAPONS: ['WOODEN_SWORD', 'STONE_SWORD', 'IRON_SWORD', 'GOLDEN_SWORD', 'DIAMOND_SWORD', 'NETHERITE_SWORD', 'BOW', 'CROSSBOW', 'TRIDENT'],
    ARMOR: ['LEATHER_HELMET', 'LEATHER_CHESTPLATE', 'LEATHER_LEGGINGS', 'LEATHER_BOOTS', 'IRON_HELMET', 'IRON_CHESTPLATE', 'IRON_LEGGINGS', 'IRON_BOOTS', 'DIAMOND_HELMET', 'DIAMOND_CHESTPLATE', 'DIAMOND_LEGGINGS', 'DIAMOND_BOOTS'],
    TOOLS: ['WOODEN_PICKAXE', 'STONE_PICKAXE', 'IRON_PICKAXE', 'DIAMOND_PICKAXE', 'WOODEN_AXE', 'STONE_AXE', 'IRON_AXE', 'DIAMOND_AXE'],
    ITEMS: ['DIAMOND', 'EMERALD', 'GOLD_INGOT', 'IRON_INGOT', 'COAL', 'REDSTONE', 'LAPIS_LAZULI']
};

window.Materials = Materials;
