// Mob Types Database
const MobTypes = {
    HOSTILE: ['ZOMBIE', 'SKELETON', 'CREEPER', 'SPIDER', 'ENDERMAN', 'WITCH', 'BLAZE', 'GHAST', 'WITHER_SKELETON', 'PHANTOM'],
    PASSIVE: ['COW', 'PIG', 'SHEEP', 'CHICKEN', 'HORSE', 'DONKEY', 'LLAMA', 'PARROT', 'RABBIT'],
    NEUTRAL: ['WOLF', 'POLAR_BEAR', 'PANDA', 'BEE', 'IRON_GOLEM', 'ENDERMAN', 'ZOMBIFIED_PIGLIN'],
    BOSS: ['ENDER_DRAGON', 'WITHER'],
    AQUATIC: ['DOLPHIN', 'SQUID', 'TROPICAL_FISH', 'COD', 'SALMON', 'PUFFERFISH', 'TURTLE']
};

window.MobTypes = MobTypes;
